Change use of long double to double.
arbor-sim/arbor pull request #1246
Opened 2020-11-17 15:39 UTC by brenthuisman

Fix for #1245.

2020-11-17 15:41 UTC, halfflat commented
We'd have to changed the uses of `long double` to `double` in `modcc` too.

2020-11-17 15:48 UTC, brenthuisman commented
What about `long long`? I think those are OK, but please confirm :)

2020-11-17 15:58 UTC, halfflat commented
I think we can consider changing `long long` to an explicit width type as something to consider in the scope of a different PR.

2020-11-17 16:24 UTC, bcumming requested changes
Does this fix the test on WSL? I thought that the problem was that on WSL the `long double` was being treated as a `double`. If so, using `double` will still create the incorrect result.

How about we instead update the test to test for relative error, and not absolute error? I would like to keep the explicit, more accurate, compile time `long double` if possible.

2020-11-17 16:24 UTC, bcumming commented on test/unit-modcc/test_parser.cpp
> +        // function uses double for intermediate results (like constant
This comment no longer makes sense.

2020-11-17 17:00 UTC, halfflat commented
My issue with `long double` is that it bakes in a platform-dependent numerical interpretation in generated code, making reproducibility harder; it's not just that the specific numerical environment would need to be recreated (if this is indeed possible), but this has to be done on the platform that runs `modcc` _as well_ as on the execution platform.

It's not too stringent a requirement, I think, that we demand IEEE double precision semantics everywhere for correctness and reproducibility, but expecting `long double` behaviour to be the same everywhere is unreasonable.

2020-11-17 18:31 UTC, thorstenhater commented
Question: What was the rationale for using long double in the first place?

2020-11-17 20:03 UTC, bcumming commented
Rationale was that it was at least as accurate as double, likely more so. If we were going to do folding, might as well make it accurate. That was before I knew what I know now.

2020-11-18 08:57 UTC, brenthuisman commented on test/unit-modcc/test_parser.cpp
> +        // function uses double for intermediate results (like constant
I'll remove it.

2020-11-18 09:05 UTC, brenthuisman commented
The PR at present does make the unit-modcc test pass on Windows WSL.

2020-11-19 11:49 UTC, bcumming approved these changes

2020-11-19 11:49 UTC, merged