Refactor `algorithms.hpp`
arbor-sim/arbor pull request #1354
Opened 2021-02-05 16:04 UTC by noraabiakar

* Refactor the functions from `algorithms.hpp`:
  - `mean`: moved to `profile/meter_manager.cpp`
  - `make_index`: moved to `util/index.hpp`
  - `is_strictly_monotonic_increasing`: moved to `/backends/gpu/forest.hpp`
  - `has_contiguous_compartments`:  moved to `/backends/gpu/forest.hpp`.
  - `branches`: moved to `/backends/gpu/forest.hpp`.
  - `expand_branches`: moved to `/backends/gpu/forest.hpp`.
  - `tree_reduce`: moved to `/backends/gpu/forest.hpp`.
  - `is_minimal_degree`: moved to `tree.hpp`.
  - `child_count`: moved to `tree.hpp`.
  - `in_interval`: not used, deleted.
  - `is_strictly_monotonic_decreasing`: not used, deleted.
  - `all_positive`:  not used, deleted.
  - `all_negative`: not used, deleted.
  - `find_branch`: not used, deleted.
  - `is_unique`: not used, deleted.
  - `binary_find`: not used, deleted.
* Remove `make_parent_index` from `tree.hpp`: not used. 
* Add unit tests to `test_forest.cpp`, `test_tree.cpp` and `test_index.cpp`

 Fixes #539

2021-02-05 16:49 UTC, halfflat requested changes
Glad to see this cleaned up!

There's one comment about the mean function (it was previously simultaneously too general and too specific), and I'm wondering if we can replace the uses of `make_index` with `make_partition`. I've never really been happy with the name `make_index`, to be honest; what do you think about a name such as `left_scan` or `scanl`?

2021-02-05 16:49 UTC, halfflat commented on arbor/profile/meter_manager.cpp
> +
There was always a latent issue in `mean` where the mean of sequence over an integral type would give an integral result. In this context, in `meter_manager.cpp`, it's always assigned to a double value, and so I think it's worthwhile making it a bit more correct and a bit less general, with e.g. `template <typename C> double mean(const C& c) { return util::sum(c)/(double)std::size(c); }`

2021-02-05 16:49 UTC, halfflat commented on arbor/communication/communicator.cpp
> +    connection_part_ = util::make_index(src_counts);
`util::make_partition` is a possible alternative here (from `util/partition.hpp`).

2021-02-08 09:52 UTC, noraabiakar commented
I've replaced all instances of `util::make_index` with `util::make_partition`, which I think are equivalent. 
In `tree.cpp`, I've removed the `memory::copy` call because I don't think it's necessary. As far as I can tell none of the vectors used live on the GPU.

2021-02-08 09:52 UTC, noraabiakar commented
bors try

2021-02-10 08:50 UTC, noraabiakar commented
bors try

2021-02-11 09:04 UTC, noraabiakar commented
bors try

2021-02-11 15:06 UTC, bcumming commented
bors try

2021-02-15 11:41 UTC, halfflat approved these changes
All good! Sorry for the delay in approval.

2021-02-15 11:43 UTC, merged