Add phase parameter to current clamps.
arbor-sim/arbor pull request #1474
Opened 2021-04-01 15:08 UTC by halfflat

* `i_clamp` constructors take new optional phase argument.
* Pulse or box envelope clamps are now provided by the static method `i_clamp::box`, taking onset, duration, and amplitude parameters.
* Bump pybind11 version so we can have keyword-only arguments in the Python API.
* Make frequency and phase keyword-only arguments to Python `iclamp`.
* Change freuqnecy units for clamps from Hz to kHz for consistency with other interfaces.

Fixes #1454.

2021-04-01 15:08 UTC, halfflat commented
bors try

2021-04-01 15:45 UTC, halfflat commented
bors try

2021-04-01 16:14 UTC, halfflat commented
bors try

2021-04-06 07:40 UTC, noraabiakar requested changes
Looks good!
I found one typo, and there's also the docs for ACC that weren't modified: https://arbor.readthedocs.io/en/latest/fileformat/cable_cell.html#label-current-clamp-envelope-pulse-delay-real-duration-real-amplitude-real-freq-real

2021-04-06 07:40 UTC, noraabiakar commented on doc/concepts/decor.rst
> +The stimulus is described by theww parameters:
Typo 'three'

2021-04-07 07:50 UTC, noraabiakar approved these changes

2021-04-08 07:30 UTC, merged