Add S-Exp for CV Policies
arbor-sim/arbor pull request #1511
Opened 2021-04-30 09:00 UTC by thorstenhater

Closes #1334

2021-05-04 12:59 UTC, noraabiakar reviewed
Should this be in arborio? It would save a bit of code duplication.

2021-05-04 13:05 UTC, thorstenhater commented
The code I duplicated (and I am unhappy about that, as discussed earlier today) is from `morph/label_parse.hpp`.
There are some common bits that could be extracted. @halfflat is working on a more principled solution.

That said, this is not primarily for I/O, so I am not sure this is justified. Also, by this argument, `label_parse.hpp` should
be part of arborio, too?!

2021-05-04 13:42 UTC, noraabiakar commented
Yes, that’s what I proposed in #1419, but I think not everyone agrees yet. 
I think it fits better in arborio.

2021-05-05 05:38 UTC, thorstenhater commented
Ok, I think I can get behind that. Also, some bits of the internal machinery could be pulled out into a single header.
I'll edit #1419 to include these suggestions and we can make a PR for the whole clean-up operation.

2021-05-12 05:53 UTC, thorstenhater commented
In a later PR, since older changes will be re-organised as well.

2021-05-12 06:52 UTC, noraabiakar requested changes
I think we should move the implementation into `arborio` before merging. As it stands, this PR adds a new public header, and doesn't fix the issue of printing the CV policy in ACC. Is there any reason why we can't move this to `arborio`?

2021-05-12 11:00 UTC, thorstenhater commented
The only reason is that the discussion in #1419 is not finished and this would half-decide / half-implement the issue.
So, if we have an agreement on #1419, sure.

2021-05-14 09:17 UTC, noraabiakar commented
This PR adds a new functionality: adding s-expression parsers for CV-policies. The infrastructure needed (the copied code) already exists in `arborio`, and is a natural fit for the new functionality. 
#1419 was proposed to unify s-expression parsing in the `arborio` library, thus removing s-expression support from the `arbor` library. Merging this PR as is would increase the amount of work needed for #1419, not to mention that it exposes a new public header file. 
I'd rather see the changes in `arborio` now, since there's nothing preventing them from being there.

2021-05-17 08:44 UTC, thorstenhater commented
To repeat: the copied code is _also_ in arbor proper, since this is where I copied it from. Also, let's get consensus on #1419 first, then we can decide where these things should go. Maybe the proper solution is a third location that can be used by both arborio and arbor?

2021-05-17 09:44 UTC, noraabiakar commented
The repository currently has the same chunk of code twice: once in `arbor` and once in `arborio` (there's an open issue to fix this: #1419); this PR would add an extra copy to `arbor`. It also adds a new public header file. I believe both the duplicated code and the new header are unnecessary and will have to be removed later. We could merge this and fix later, but there's a simple fix that we can do now: move the implementation to `arborio`, where it will most likely end up eventually anyway.

Also, I think merging the PR as it is would go against the "Boy Scout Rule" of leaving the code in a better shape than before. 3x duplicated is not better than 2x duplicated :slightly_smiling_face:

2021-05-17 14:10 UTC, thorstenhater commented
While you are correct in pointing out the issue in duplicating that chunk of code again, I would argue that a principled solution is easy to achieve by having consensus in #1419 first. Also, the duplication over arbor/arborio should never have happened in the first place and also should be cleaned up by #1419. *Then* we would be following the Boy Scout rule.

2021-06-01 08:00 UTC, noraabiakar commented on arborio/cv_policy_parse.cpp
> +                             "'every-segment' with one argument (every-segment <region-expr>)")},
Small nitpick: in the other parsers, the style of the message is like this: 
```
'every-segment' with one argument (reg:region)
```
If it's not too much work can we unify the representation?

2021-06-01 09:06 UTC, noraabiakar requested changes
Looks good! Thanks for taking care of the refactoring :) 
I have a few minor comments. 
There's also still a bit of duplication in the `eval` functions in `arborio`, but that can be dealt with in another PR. We should also discuss unifying the docs for the s-expressions.

2021-06-01 09:06 UTC, noraabiakar commented on python/single_cell_model.cpp
> +                m.probe(what, *arborio::parse_locset_expression(where), frequency);},
Possible unhelpful exception.

2021-06-01 12:31 UTC, thorstenhater commented on arborio/cv_policy_parse.cpp
> +//      cv_policy: a region
:+1:

2021-06-01 12:32 UTC, thorstenhater commented on python/cable_probes.cpp
> +    return arb::cable_probe_membrane_voltage{*arborio::parse_locset_expression(where)};
We did not before, so this keeps the semantics?

2021-06-01 12:32 UTC, thorstenhater commented on arborio/include/arborio/label_parse.hpp
> +arb::region operator "" _rg(const char* s, std::size_t) {
We could, but then it would have 3 letters instead of 2 like `ls`. That would break all the nice alignment.

2021-06-01 12:33 UTC, thorstenhater commented on arborio/cv_policy_parse.cpp
> +                                "'add' with at least 2 arguments: (join cv_policy cv_policy ...)")},
👍

2021-06-01 12:33 UTC, thorstenhater commented on arborio/cv_policy_parse.cpp
> +                                     "'explicit' with one argument (explicit <locset-expr> <region-expr>)")},
👍

2021-06-01 12:33 UTC, thorstenhater commented on arborio/cv_policy_parse.cpp
> +                             "'every-segment' with one argument (every-segment <region-expr>)")},
👍

2021-06-02 07:07 UTC, thorstenhater commented on python/cable_probes.cpp
> +    return arb::cable_probe_membrane_voltage{*arborio::parse_locset_expression(where)};
Ok, it's slightly different. Fixed.

2021-06-03 08:55 UTC, noraabiakar approved these changes

2021-06-03 09:07 UTC, noraabiakar requested changes
Ah I forgot, I think `arbor/include/s_expr.hpp` and `arbor/s_expr.cpp` can now be moved to `arborio`

2021-06-28 09:40 UTC, thorstenhater commented
Files have been moved.

2021-06-29 09:30 UTC, noraabiakar approved these changes
Looks good!

2021-06-29 09:50 UTC, merged