Guard empty ARB_CXXOPT_ARCH, cf. spack package
arbor-sim/arbor pull request #1518
Opened 2021-05-05 07:45 UTC by schmitts

Please make sure your PR follows our [contribution guidelines](https://github.com/arbor-sim/arbor/tree/master/doc/contrib) and agree to the terms outlined in the [PR procedure](https://github.com/arbor-sim/arbor/tree/master/doc/contrib/pr.rst).

2021-05-05 08:37 UTC, bcumming commented
@schmitts , can you please update the PR description to describe why/what this is for? Is it fixing a problem?

2021-05-07 12:10 UTC, brenthuisman commented
It's not clear why are the tests failing to compile. Any idea?

2021-05-07 14:48 UTC, schmitts commented
> It's not clear why are the tests failing to compile. Any idea?

I don't see what's going on. Let's see if #1519 helps.

2021-05-10 10:20 UTC, brenthuisman commented
I reran the job but they still fail. Is the problem what you described in Slack (`march`, `Abi = arb::simd::simd_abi::native`, etc.)?

2021-05-10 10:44 UTC, schmitts commented
> I reran the job but they still fail. Is the problem what you described in Slack (`march`, `Abi = arb::simd::simd_abi::native`, etc.)?

Yes. I'm putting together a summary atm.

2021-05-11 04:56 UTC, bcumming commented
Unfortunately I missed the slack conversation where the issue that this is addressing was discussed.

Can we have a GitHub issue that describes the problem.

To the best of my knowledge, the `ARB_ARCH` variable can't be empty, unless the user manually sets it `-DARB_ARCH=""`.

2021-05-11 06:14 UTC, schmitts commented
> Unfortunately I missed the slack conversation where the issue that this is addressing was discussed.
> 
> Can we have a GitHub issue that describes the problem?
> 
> To the best of my knowledge, the `ARB_ARCH` variable can't be empty, unless the user manually sets it `-DARB_ARCH=""`.

Cf. #1522.

2021-05-26 07:54 UTC, bcumming requested changes
At the moment tests are failing, and they are related to SIMD on Linux.

Only one use of `ARB_CXXOPT_ARCH` is being guarded in the changes here. What about the others?

2021-05-26 07:54 UTC, bcumming commented on CMakeLists.txt
> +    set(MAYBE_EMPTY_ARB_ARCH "notset")
Should we also set `ARB_CXXOPT_ARCH=""` here, so that it is explicitly set as empty when used later?

2021-05-26 07:54 UTC, bcumming commented on mechanisms/BuildModules.cmake
> +	set_source_files_properties(${catalogue_${MK_CAT_NAME}_source} COMPILE_FLAGS ${ARB_CXXOPT_ARCH})
the `ARB_CXXOPT_ARCH` variable is used elsewhere in the CMake configureation, so should we explicitly set it to an empty string?
```
bcumming@arapiles:arbor > ag ARB_CXXOPT_ARCH
python/test/cpp/CMakeLists.txt
15:target_compile_options(py_unit PRIVATE ${ARB_CXXOPT_ARCH})

mechanisms/BuildModules.cmake
77:    message("Arbor arch:           ${ARB_CXXOPT_ARCH}")
121:  set_source_files_properties(${catalogue_${MK_CAT_NAME}_source} COMPILE_FLAGS ${ARB_CXXOPT_ARCH})

test/unit/CMakeLists.txt
238:target_compile_options(unit PRIVATE ${ARB_CXXOPT_ARCH})

test/ubench/CMakeLists.txt
29:    target_compile_options(${bench_exe} PRIVATE ${ARB_CXXOPT_ARCH})

test/unit-distributed/CMakeLists.txt
14:target_compile_options(unit-local PRIVATE ${ARB_CXXOPT_ARCH})
22:    target_compile_options(unit-mpi PRIVATE ${ARB_CXXOPT_ARCH})

cmake/arbor-config.cmake.in
52:set(ARB_CXXOPT_ARCH @ARB_CXXOPT_ARCH@)

sup/CMakeLists.txt
10:target_compile_options(arbor-sup PRIVATE ${ARB_CXXOPT_ARCH})

CMakeLists.txt
234:    set_arch_target(ARB_CXXOPT_ARCH "${ARB_ARCH}")
235:    target_compile_options(arbor-private-deps INTERFACE ${ARB_CXXOPT_ARCH})
236:    target_compile_options(arborenv-private-deps INTERFACE ${ARB_CXXOPT_ARCH})
```

2021-06-16 06:51 UTC, schmitts commented
parsing `march` (as done in https://github.com/schmitts/arbor/commit/01dd2e5315cfaea46f728ebdbed0a7a995c75b95) is not enough as some targets use `mcpu`, cf. https://github.com/arbor-sim/arbor/blob/master/cmake/CompilerOptions.cmake#L115 @bcumming and @halfflat are working on an alternative to pass in user defined optimization falgs.

2021-07-05 05:43 UTC, bcumming commented
The problem that this is fixing was addressed in #1586

2021-07-05 05:43 UTC, closed without merging