Ci/sanitize
arbor-sim/arbor pull request #1521
Opened 2021-05-10 12:45 UTC by thorstenhater

Fix a typo.

2021-05-11 04:53 UTC, bcumming commented
This expands the number of CI jobs significantly by using the sanitizer on configurations, increasing the amount of computational resources on every commit to a PR, and increasing time taken to run tests. It will also add maintenance overheads for the CI tests, which we have to balance against the modest benefits of running the sanitizer.

Instead, can we run it on one configuration automatically by default? We could trigger the other configurations manually.

2021-05-11 06:09 UTC, thorstenhater commented
Hi,

this is a fix to the original PR which was merged already, but has the same name.

The reason for using both SIMD and Scalar is that changes to modcc can break
the generated mechanisms and introduce issues in modcc itself. The rest of the
configuration does not change. We can also not run multiple sanitizers on the same
target, as they exclude each other.

While I agree on the amount of resources increasing, I am less sure about the other
arguments. The time will likely not increase, as all tests can run in parallel. The maintenance
requirements are minimal and will have to be done to all of our CI jobs.

Originally we opted for running this nightly, but changed that sentiment in a discussion.
Likely that was because it's easier to fix these issues while introducing them.

2021-05-20 10:15 UTC, halfflat requested changes

2021-05-20 12:42 UTC, thorstenhater commented on example/dryrun/dryrun.cpp
> +        params.defaulted = false;
If we have that, it's not widely used:
```
rg -t cpp -c '\} else \{' arbor          Thu May 20 14:41:58 2021
arbor/arbor/tree.cpp:1
arbor/arbor/partition_load_balance.cpp:1
arbor/arbor/backends/gpu/forest.hpp:3
arbor/arbor/backends/gpu/matrix_state_fine.hpp:2
arbor/arbor/util/unwind.cpp:1
arbor/arbor/morph/region.cpp:2
arbor/example/dryrun/dryrun.cpp:1
arbor/modcc/expression.cpp:1
arbor/modcc/solvers.cpp:3
arbor/modcc/linearrewriter.cpp:1
arbor/modcc/symge.cpp:1
arbor/modcc/module.cpp:6
arbor/modcc/functioninliner.cpp:3
arbor/modcc/printer/cprinter.cpp:14
arbor/modcc/printer/cexpr_emit.cpp:7
arbor/test/gtest-all.cpp:47
arbor/test/gtest.h:11
arbor/test/unit/test_lif_cell_group.cpp:1
arbor/test/unit/test_mechcat.cpp:1
arbor/test/unit/test_fvm_lowered.cpp:1
arbor/test/unit-modcc/test_parser.cpp:1
arbor/test/unit-modcc/test_fn_rewriters.cpp:2
```

2021-05-20 12:44 UTC, thorstenhater commented on example/dryrun/dryrun.cpp
>          }
The reason that this is here is that the sanitizers run with assertions enabled. Thus this will raise an assertion error later on.

2021-05-20 12:45 UTC, thorstenhater commented on example/dryrun/dryrun.cpp
>          }
Also: Our normal CI does not have assertions enabled.

2021-05-20 12:50 UTC, thorstenhater commented on example/dryrun/dryrun.cpp
>          }
That said, currently MPI has been excluded in any case due to memory leaks. So, I can remove this for the moment.

2021-05-20 13:34 UTC, halfflat commented on example/dryrun/dryrun.cpp
> +        params.defaulted = false;
`modcc` is a whole separate story; conventions there are different.

2021-05-20 13:43 UTC, halfflat commented on example/dryrun/dryrun.cpp
> +        params.defaulted = false;
So, for comparison:
```
% rg -c '^\s*\}\s*else\s*\{' arbor
arbor/partition_load_balance.cpp:1
arbor/tree.cpp:1
arbor/morph/region.cpp:2
arbor/backends/gpu/forest.hpp:3
arbor/backends/gpu/matrix_state_fine.hpp:2
arbor/util/unwind.cpp:1
```
```
% rg -c -U '^\s*\}\s*$\n\s*else\s*\{' arbor
arbor/cv_policy.cpp:2
arbor/event_queue.hpp:1
arbor/fvm_layout.cpp:9
arbor/mc_cell_group.cpp:1
arbor/partition_load_balance.cpp:1
arbor/mechcat.cpp:12
arbor/fvm_lowered_cell_impl.hpp:3
arbor/s_expr.cpp:5
arbor/simulation.cpp:2
arbor/tree.cpp:1
arbor/communication/communicator.cpp:1
arbor/morph/embed_pwlin.cpp:2
arbor/morph/label_parse.cpp:3
arbor/io/locked_ostream.cpp:1
arbor/morph/place_pwlin.cpp:2
arbor/morph/locset.cpp:2
arbor/morph/mprovider.cpp:2
arbor/morph/morphology.cpp:7
arbor/morph/primitives.cpp:1
arbor/morph/region.cpp:3
arbor/morph/stitch.cpp:1
arbor/profile/profiler.cpp:2
arbor/profile/meter_manager.cpp:2
arbor/util/cycle.hpp:3
arbor/util/filter.hpp:1
arbor/util/mergeview.hpp:1
arbor/util/ordered_forest.hpp:2
arbor/util/ratelem.hpp:4
arbor/util/sentinel.hpp:1
arbor/util/piecewise.hpp:1
arbor/util/transform.hpp:1
arbor/backends/multicore/matrix_state.hpp:1
arbor/backends/multicore/mechanism.cpp:2
arbor/backends/multicore/partition_by_constraint.hpp:2
arbor/backends/multicore/multi_event_stream.hpp:1
arbor/backends/multicore/threshold_watcher.hpp:1
arbor/backends/gpu/matrix_assemble.cu:2
arbor/backends/gpu/mechanism.cpp:2
arbor/include/arbor/simple_sampler.hpp:1
arbor/include/arbor/util/any_ptr.hpp:1
```

2021-05-21 12:53 UTC, thorstenhater commented on .github/workflows/sanitize.yml
> +          make -j4 VERBOSE=1 tests examples
We have to, for reason that are highly annoying:
- The sanitizer runtime is usually linked statically, but that does not work with shared objects.
- Why? No idea. I would have assumed that statically linking libarbor.a against libsan.a and libpyarb.so against libarbor.a would be enough. But it's not, we get errors of the variety 'undefined symbol asan_<...>' from the python wrappers
- One can, however, build a shared object runtime and LD_PRELOAD it. Which requires building clang from scratch with SAN_DSO enabled. This is not proportional to the expected benefit I think.

2021-05-21 13:04 UTC, halfflat commented on .github/workflows/sanitize.yml
> +          make -j4 VERBOSE=1 tests examples
No worries! I mean, yes it sounds terrible, but we can come back to this later if we think it's worth all the effort.

2021-05-21 13:04 UTC, halfflat commented on example/dryrun/dryrun.cpp
>          }
Yes, let's do that, and I'll make an issue about the UI.

2021-05-21 13:05 UTC, halfflat commented on .github/workflows/sanitize.yml
> +          make -j4 VERBOSE=1 tests examples
Or actually, just keep it in — saves amending the PR. I'll make the issue regardless.

2021-05-21 13:16 UTC, halfflat commented on example/dryrun/dryrun.cpp
>          }
Or actually, just keep it in — saves amending the PR. I'll make the issue regardless. (EDIT: moved this comment to the right conversation, sorry!)

2021-07-22 12:56 UTC, halfflat requested changes
All looks good save for that preload bit, which we discussed in chat.

2021-07-22 12:56 UTC, halfflat commented on .github/workflows/sanitize.yml
> +          export LD_PRELOAD=$(clang -print-file-name=libclang_rt.san-x86_64.so)
The preload is generating a bunch of warnings in the build log; can be removed (pers. comm. with @thorstenhater).

2021-07-23 11:14 UTC, halfflat approved these changes

2021-07-23 11:16 UTC, merged