Improved documentation about weights
arbor-sim/arbor pull request #1620
Opened 2021-08-03 14:48 UTC by brenthuisman

In response to some questions at the IBRO-Ebrains workshop, here some minor updates in the documentation of connection and event generator weights.

2021-08-03 15:07 UTC, schmitts reviewed
LGTM

2021-08-10 12:03 UTC, halfflat requested changes

2021-08-10 12:03 UTC, halfflat commented on doc/python/interconnectivity.rst
> +
The only change I'd suggest here is to remove the mention of distributed processes, as these cannot be targets of connections.

2021-08-10 12:03 UTC, halfflat commented on doc/python/recipe.rst
> +        For Arbor-supplied distributed processes, ``weight = 1`` induces ``1`` [S/cm2].
As above, re: distributed processes.

2021-08-10 12:03 UTC, halfflat commented on doc/tutorial/network_ring.rst
> +previous cell has a gid ``(gid-1)%self.ncells``. The connection has a weight of 0.01 μS and a delay of 5 ms.
We shouldn't have the unit here on the weight.

2021-08-10 12:03 UTC, halfflat commented on python/example/network_ring.py
> +        w = 0.01 # μS on expsyn
Just to make it clear, I'd propose the comment `# 0.01 μS on expsyn` here and below.

2021-08-10 12:18 UTC, halfflat approved these changes
Thanks for the edits!

2021-08-10 12:55 UTC, merged