Give parameter useful name.
arbor-sim/arbor pull request #1678
Opened 2021-09-22 11:55 UTC by brenthuisman

Fixes #1666

2021-09-22 13:04 UTC, Helveg approved these changes
Looks good on the Python side, can use `arbor.mechanism(name=...)` and fixed docstring:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. arbor._arbor.mechanism(name: str)
    2. arbor._arbor.mechanism(name: str, params: Dict[str, float])
```

2021-09-29 08:12 UTC, noraabiakar requested changes
Looks good thanks! I have a few small suggestions.

2021-09-29 08:12 UTC, noraabiakar commented on python/cells.cpp
> +            "Construct with a morphology.")
This constructs with a morphology, label dictionary and decor.

2021-09-29 08:12 UTC, noraabiakar commented on python/cells.cpp
> +            "s"_a, "A valid CV policy expression")
Maybe we can give this an argument name more descriptive than "s"?

2021-10-04 08:34 UTC, noraabiakar approved these changes

2021-10-04 08:35 UTC, merged