Documentation: add expected nmodl units
arbor-sim/arbor pull request #1756
Opened 2021-11-12 13:45 UTC by noraabiakar

Fixes #1753

2021-11-12 15:41 UTC, schmitts requested changes
Apart from the minor fixups, Arbor experts need to check the units

2021-11-12 15:41 UTC, schmitts commented on doc/fileformat/nmodl.rst
> +conductivity (density mechanisms)                identifier inferred from current_denisty equation    S/cm²
typo: denisty

2021-11-12 19:32 UTC, bcumming approved these changes
lgtm

2021-11-12 19:32 UTC, merged

2021-11-16 13:04 UTC, jlubo commented
Thanks! This will help a lot reproducing results from other simulations.