Expose information about the CV discretization to the public inteface
arbor-sim/arbor pull request #1758
Opened 2021-11-12 14:46 UTC by noraabiakar

Refactor the CV-cable logic from `fvm_layout.cpp`. Specifically, move `cv_geometry_from_ends` into the new public header `cv_data.hpp` and rename it to `cv_data_from_locset`, and move `pw_over_cable` into another new public header `util/piecewise_over_cable.hpp`. 
Create a new public class `cell_cv_data`, similar to the private `cv_geometry` but which only carries the cv information for a single cable-cell. Add a new constructor to `cv_geometry` which takes `cell_cv_data` as an argument. 
Add new public function `intersect_region` that takes as arguments a cable-cell, a region on that cell and a `cell_cv_data` object and returns a vector of CV indices and proportions belonging to the region. 
Add docs, python wrapper and unit tests. 

Fixes #1720.

2022-01-06 13:41 UTC, bcumming requested changes

2022-01-06 13:41 UTC, bcumming commented on arbor/morph/cv_data.cpp
> +        return {};
already fixed.

2022-01-06 13:41 UTC, bcumming commented on arbor/include/arbor/morph/cv_data.hpp
> +    std::vector<mcable> cv_cables;                // CV unbranched sections, partitioned by CV.
already fixed.

2022-01-06 14:16 UTC, noraabiakar commented on arbor/fvm_layout.hpp
> +    cv_geometry(cell_cv_data data) :
All the methods of the class are implemented in the header file. Should I move those too?

2022-01-07 13:52 UTC, bcumming approved these changes

2022-01-07 13:53 UTC, merged