Bug fix: Fix voltage vector size in threshold_watcher contstructor
arbor-sim/arbor pull request #1820
Opened 2022-01-27 17:03 UTC by noraabiakar

Fix the following 2 issues: 
- `threshold_watcher::v_prev_` is being constructed from a pointer to `shared_state::voltage` and a size argument not equal to the size of that vector. This isn't usually a problem because the size used is typically less that the maximum size of the `voltage` vector. However, it can cause problems if that assumption fails. 
- `v_prev_` is copied over from `shared_state::voltage` before that vector is initialized to `init_voltage` in `shared_state::reset`. This can cause incorrect results at the very first application of `threshold_watcher::test`.

2022-01-28 08:34 UTC, noraabiakar commented
bors try

2022-01-31 08:16 UTC, noraabiakar commented
bors try

2022-02-02 16:03 UTC, thorstenhater requested changes
A suggestion, rest looks fine.

2022-02-02 16:03 UTC, thorstenhater commented on arbor/backends/multicore/threshold_watcher.hpp
> +        // reset() needs to be called before this is ready for use
Same as above.

2022-02-02 17:03 UTC, noraabiakar commented on arbor/backends/gpu/threshold_watcher.hpp
> +        // reset() needs to be called before this is ready for use
So, this change is meant to align more with the behavior of `reset` in other classes (mainly the `shared_state` and `fvm_lowered_cell`) where `reset` is used to both initialize and reset the class. 
With these changes, we rely on the `fvm_lowered_cell` to call `threshold_watcher::reset` after constructing it and before using it, which it does.

2022-02-02 17:07 UTC, thorstenhater commented on arbor/backends/gpu/threshold_watcher.hpp
> +        // reset() needs to be called before this is ready for use
I appreciate the homogeneity in the code. However I was worried someone might miss this part of the contract 
(you must `reset` before calling `is_crossed(ix)` or receive nonsense). You stated it in the comment here, but
it's still easy to miss.

2022-03-23 11:39 UTC, noraabiakar commented
bors try

2022-03-29 09:24 UTC, noraabiakar commented
bors try

2022-03-29 10:59 UTC, noraabiakar commented
bors try

2022-05-05 06:55 UTC, thorstenhater approved these changes
👍

2022-05-05 06:56 UTC, merged