Add point probes to demo
arbor-sim/arbor pull request #1891
Opened 2022-05-11 09:13 UTC by schmitts

2022-06-02 11:41 UTC, thorstenhater requested changes
Thanks for adding this! A C++ism and then we are good to merge.

2022-06-02 13:17 UTC, thorstenhater approved these changes
👍

2022-06-03 06:55 UTC, brenthuisman requested changes
I believe this is the showstopper.

2022-06-03 06:55 UTC, brenthuisman commented on example/probe-demo/probe-demo.cpp
> +        assert(n_entities==hi-low);
```suggestion
        assert(n_entities==hi-lo);
```

2022-06-03 07:19 UTC, schmitts commented
> I believe this is the showstopper.

I was compiling in `release` that nulls the asserts ...

2022-06-03 09:16 UTC, brenthuisman approved these changes

2022-06-03 09:16 UTC, merged