Add more visibility to decor.
arbor-sim/arbor pull request #1953
Opened 2022-08-19 18:19 UTC by thorstenhater

Functionality to
- delete ions from global properties
- peek into global properties
- expose painted, placed, and defaulted items

Closes #1578 
Closes #1577

2022-08-22 07:12 UTC, AdhocMan requested changes
Just a few comments that need updating as well

2022-08-22 09:27 UTC, thorstenhater commented on arbor/fvm_lowered_cell_impl.hpp
>      // Non-physical voltage check threshold, 0 => no check.
Good catch.

2022-08-22 11:07 UTC, AdhocMan approved these changes
Looks good to me.
I'll leave the merge commit message to you on this one.

2022-08-22 12:34 UTC, brenthuisman requested changes
Missing updates to Python API, e.g. `python/decor.rst`.

2022-08-23 12:09 UTC, brenthuisman approved these changes

2022-08-23 12:09 UTC, merged