Do not restrict SWC record identifier
arbor-sim/arbor pull request #1996
Opened 2022-10-04 11:07 UTC by schmitts

All integers do occur in the wild according to:

http://www.neuronland.org/NLMorphologyConverter/MorphologyFormats/SWC/Spec.html

Standardized swc files (www.neuromorpho.org) -
0 - undefined
1 - soma
2 - axon
3 - (basal) dendrite
4 - apical dendrite
5+ - custom

A lot of data does not conform exactly to this standard however e.g.

CNIC data -
0 - undefined
1 - soma
2 - axon
3 - (basal) dendrite
4 - apical dendrite
5 - fork point
6 - end point
7 - custom

VNED data -  seems to be standard, but uses
10 - related to soma ?

Gulyas data - each number represents structure with same diameter.

Other data has been observed with
-1 -  also possibly related to soma ?

2022-10-04 11:10 UTC, thorstenhater requested changes
Since Arbor does not imbue these tags with special meaning I see no reason to restrict them.
Before I approve, have you checked the docs/tests are ok?

2022-10-05 06:05 UTC, schmitts commented
"All checks have passed" and I couldn't find any explicit mention of allowed SWC identifier in the Arbor docs. Maybe @brenthuisman knows a potential spot?

2022-10-05 06:07 UTC, thorstenhater commented
👍 

Could you add the table you quoted (and its source!) to the docs at
https://docs.arbor-sim.org/en/latest/fileformat/swc.html

2022-10-11 09:39 UTC, brenthuisman commented
`fileformat/swc.rst` is indeed the place where current conventions are documented. An update to it would be appreciated!

2022-10-11 09:39 UTC, schmitts commented
@brenthuisman Yes, I'll update the PR and add some links and docs.

2022-10-11 10:49 UTC, schmitts commented
Going through https://docs.arbor-sim.org/en/latest/fileformat/swc.html I don't see a need to add anything.

2022-10-11 12:44 UTC, thorstenhater approved these changes

2022-10-11 15:05 UTC, merged