Fix incorrect mention of attribute `catalogue` in `single_cell_model`
arbor-sim/arbor pull request #2122
Opened 2023-05-17 11:07 UTC by Helveg

2023-05-17 11:28 UTC, thorstenhater submitted a review, later dismissed
Nice find!

2023-05-30 08:47 UTC, brenthuisman requested changes

2023-05-30 10:09 UTC, brenthuisman approved these changes

2023-05-30 10:10 UTC, merged

2023-05-30 10:10 UTC, brenthuisman commented
TY!