Explain spherical soma and connectedness.
arbor-sim/arbor pull request #2214
Opened 2023-08-28 11:47 UTC by thorstenhater

Extend docs to cover two topics I recently interact with. These seemed confusing to me,
so I expect more people will feel this way.

- Spherical soma in SWC and its consequence for attaching dendrites.
- Connectedness of components.

Closes #2161

2023-10-06 14:37 UTC, AdhocMan requested changes

2023-10-06 14:37 UTC, AdhocMan commented on doc/concepts/morphology.rst
> +This mean a simple fork -- as that between branches 2, 3, and 4 in the image
```suggestion
This means a simple fork -- as that between branches 2, 3, and 4 in the image
```

2023-10-06 14:37 UTC, AdhocMan commented on doc/fileformat/swc.rst
> +* All dendrites, axons, and apical dendrites attached to the center of the soma with "zero resistance wires".
```suggestion
* All dendrites, axons, and apical dendrites are attached to the center of the soma with "zero resistance wires".
```

2023-10-06 14:37 UTC, AdhocMan commented on doc/scripts/gen-labels.py
> +    print(label)
Is that a leftover?

2023-10-17 19:15 UTC, thorstenhater commented on doc/scripts/gen-labels.py
> +    print(label)
Yes.

2023-10-20 13:00 UTC, merged