fixed typos etc
arbor-sim/arbor pull request #2339
Opened 2024-07-31 07:46 UTC by ErbB4

2024-07-31 07:58 UTC, thorstenhater commented on doc/python/simulation.rst
> +        # Run the simulation for 2000 ms with a time step of 0.025 ms
These should have units ;)

2024-07-31 08:00 UTC, thorstenhater requested changes

2024-07-31 08:00 UTC, thorstenhater commented on doc/python/simulation.rst
> +        # Print the spikes and accordingly the spike time
```suggestion
        # Print the spikes: time and source 
```

2024-07-31 08:00 UTC, thorstenhater commented on doc/python/simulation.rst
> +        # Run the simulation for 2000 ms with a time step of 0.025 ms
Same here, units missing. Again, not your fault, but let's do it right

2024-07-31 15:12 UTC, thorstenhater requested changes

2024-07-31 15:12 UTC, thorstenhater commented on doc/python/simulation.rst
> +    handle = sim.sample((0, 0), A.regular_schedule(0.1))
unit!

2024-08-01 07:26 UTC, ErbB4 commented on doc/python/simulation.rst
> +    handle = sim.sample((0, 0), A.regular_schedule(0.1))
okkkkkkk

2024-08-01 08:12 UTC, thorstenhater requested changes

2024-08-01 08:12 UTC, thorstenhater commented on doc/python/simulation.rst
> +    handle = sim.sample((0, 0), A.regular_schedule(0.1))
```suggestion
    handle = sim.sample((0, 0), A.regular_schedule(0.1*U.ms))
```

2024-08-01 08:12 UTC, thorstenhater commented on doc/python/simulation.rst
> +        tSim = 2000 * U.ms
On a pure technicality: You _could_ write
```suggestion
        tSim = 2 * U.s
```
instead

2024-08-07 14:59 UTC, thorstenhater approved these changes

2024-08-07 14:59 UTC, merged